services:
  - type: web
    name: LuckyTechHub-Bot
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
